package gregicadditions;

import com.google.common.collect.ImmutableList;
import gregtech.api.unification.Element;
import gregtech.api.unification.material.MaterialIconSet;
import gregtech.api.unification.material.Materials;
import gregtech.api.unification.material.type.*;
import gregtech.api.unification.stack.MaterialStack;

public class GAMaterials {
    public static DustMaterial Brick;
    public static DustMaterial Fireclay;
    public static GemMaterial Coke;
    public static DustMaterial PhosphorusPentoxide;
    public static FluidMaterial PhosphoricAcid;
    public static FluidMaterial PolyvinylAcetate;
    public static FluidMaterial Phenol;
    public static FluidMaterial BisphenolA;
    public static IngotMaterial ReinforcedEpoxyResin;
    public static IngotMaterial BorosilicateGlass;
    public static IngotMaterial PolyvinylChloride;
    public static FluidMaterial VinylChloride;
    public static FluidMaterial Ethylene;
    public static FluidMaterial CharcoalByproducts;
    public static FluidMaterial Benzene;
    public static FluidMaterial WoodGas;
    public static FluidMaterial WoodVinegar;
    public static FluidMaterial WoodTar;
    public static DustMaterial SodiumHydroxide;
    public static DustMaterial Quicklime;
    public static FluidMaterial Acetone;
    public static FluidMaterial SulfurTrioxide;
    public static FluidMaterial SulfurDioxide;
    public static FluidMaterial Glycerol;
    public static FluidMaterial FishOil;
    public static FluidMaterial Methanol;
    public static FluidMaterial CarbonMonoxde;
    public static FluidMaterial CetaneBoostedDiesel;
    public static FluidMaterial DilutedSulfuricAcid;
    public static DustMaterial SodiumBisulfate;
    public static FluidMaterial Chloroform;
    public static FluidMaterial DilutedHydrochloricAcid;
    public static FluidMaterial HypochlorousAcid;
    public static FluidMaterial Ammonia;
    public static FluidMaterial Chloramine;
    public static FluidMaterial Dimethylamine;
    public static FluidMaterial Dimethylhydrazine;
    public static FluidMaterial RocketFuel;
    public static FluidMaterial DinitrogenTetroxide;
    public static IngotMaterial SiliconeRubber;
    public static DustMaterial Polydimethylsiloxane;
    public static FluidMaterial Dimethyldichlorosilane;
    public static FluidMaterial Styrine;
    public static IngotMaterial Polysterine;
    public static FluidMaterial Butadiene;
    public static DustMaterial RawStyrineButadieneRubber;
    public static IngotMaterial StyrineButadieneRubber;
    public static FluidMaterial Dichlorobenzene;
    public static FluidMaterial HydrochloricAcid;
    public static FluidMaterial AceticAcid;
    public static FluidMaterial FermentedBiomass;
    public static DustMaterial Potash;
    public static DustMaterial SodaAsh;
    public static FluidMaterial HydrofluoricAcid;
    public static FluidMaterial NitricOxide;
    public static FluidMaterial MethylAcetate;
    public static FluidMaterial Ethenone;
    public static FluidMaterial Tetranitromethane;
    public static FluidMaterial BioDiesel;
    public static FluidMaterial RawGrowthMedium;
    public static FluidMaterial SterilizedGrowthMedium;
    public static DustMaterial Meat;
    public static DustMaterial CookedMeat;
    public static FluidMaterial VinylAcetate;
    public static IngotMaterial GalliumArsenide;
    public static IngotMaterial PolyphenyleneSulfide;
    public static FluidMaterial NickelSulfateSolution;
    public static FluidMaterial BlueVitriolSolution;
    public static FluidMaterial Propane;
    public static FluidMaterial Propene;
    public static FluidMaterial Ethane;
    public static FluidMaterial Butene;
    public static FluidMaterial Butane;
    public static FluidMaterial CalciumAcetate;
    public static FluidMaterial Cumene;
    public static IngotMaterial IndiumGalliumPhosphide;
    public static DustMaterial PlatinumGroupSludge;

    static {
        long STD_SOLID = DustMaterial.MatFlags.GENERATE_PLATE |
                gregtech.api.unification.material.type.SolidMaterial.MatFlags.GENERATE_ROD |
                gregtech.api.unification.material.type.IngotMaterial.MatFlags.GENERATE_BOLT_SCREW;
        long STD_GEM = DustMaterial.MatFlags.GENERATE_ORE | STD_SOLID |
                gregtech.api.unification.material.type.GemMaterial.MatFlags.GENERATE_LENSE;
        long STD_METAL = DustMaterial.MatFlags.GENERATE_PLATE;
        long EXT_METAL = STD_METAL | gregtech.api.unification.material.type.SolidMaterial.MatFlags.GENERATE_ROD |
                gregtech.api.unification.material.type.IngotMaterial.MatFlags.GENERATE_BOLT_SCREW;
        long EXT2_METAL = EXT_METAL | gregtech.api.unification.material.type.SolidMaterial.MatFlags.GENERATE_GEAR |
                gregtech.api.unification.material.type.IngotMaterial.MatFlags.GENERATE_FOIL |
                gregtech.api.unification.material.type.IngotMaterial.MatFlags.GENERATE_FINE_WIRE;

        Brick = new DustMaterial(999,"brick",0xB75A40,MaterialIconSet.ROUGH,1,ImmutableList.of(new MaterialStack(Materials.Aluminium,4),new MaterialStack(Materials.Silicon,3),new MaterialStack(Materials.Oxygen,12)),Material.MatFlags.DISABLE_DECOMPOSITION | DustMaterial.MatFlags.EXCLUDE_BLOCK_CRAFTING_RECIPES);
        Fireclay = new DustMaterial(998,"fireclay",0x928073,MaterialIconSet.ROUGH,1,ImmutableList.of(new MaterialStack(Materials.Clay,1),new MaterialStack(Brick,1)),Material.MatFlags.DISABLE_DECOMPOSITION | DustMaterial.MatFlags.EXCLUDE_BLOCK_CRAFTING_RECIPES);
        Coke = new GemMaterial(997,"coke",0x6f6f80,MaterialIconSet.valueOf("COKE"),1,ImmutableList.of(new MaterialStack(Materials.Carbon,1)),Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING | SolidMaterial.MatFlags.MORTAR_GRINDABLE | Material.MatFlags.FLAMMABLE  | DustMaterial.MatFlags.NO_SMELTING | DustMaterial.MatFlags.NO_SMASHING);
        PhosphorusPentoxide = new DustMaterial(996,"phosphorus_pentoxide",0x7c7d00,MaterialIconSet.DULL,1,ImmutableList.of(new MaterialStack(Materials.Phosphorus,4),new MaterialStack(Materials.Oxygen,10)),Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        PhosphoricAcid = new FluidMaterial(995,"phosphoric_acid",0xaeae10,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Hydrogen,3),new MaterialStack(Materials.Phosphorus,4)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        PolyvinylAcetate = new FluidMaterial(994,"polyvinyl_acetate",0xc87e4c,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Carbon,4),new MaterialStack(Materials.Hydrogen,6),new MaterialStack(Materials.Oxygen,2)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK);
        Phenol = new FluidMaterial(993,"phenol",0x654027,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Carbon,6),new MaterialStack(Materials.Hydrogen,6),new MaterialStack(Materials.Oxygen,1)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        BisphenolA = new FluidMaterial(992,"bisphenol_b",0xa5870e,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Carbon,15),new MaterialStack(Materials.Hydrogen,16),new MaterialStack(Materials.Oxygen,2)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        ReinforcedEpoxyResin = new IngotMaterial(991,"reinforced_epoxy_resin",0x72500b,MaterialIconSet.DULL,1,ImmutableList.of(new MaterialStack(Materials.Carbon,6),new MaterialStack(Materials.Hydrogen,4),new MaterialStack(Materials.Oxygen,1)),DustMaterial.MatFlags.GENERATE_PLATE, (Element)null,6.0F, 64);
        BorosilicateGlass = new IngotMaterial(990,"borosilicate_glass",0xccd7cc,MaterialIconSet.METALLIC,1,ImmutableList.of(new MaterialStack(Materials.Boron,1),new MaterialStack(Materials.SiliconDioxide,7)),Material.MatFlags.DISABLE_DECOMPOSITION);
        PolyvinylChloride = new IngotMaterial(989,"polyvinyl_chloride",0x99a4a4,MaterialIconSet.DULL,1,ImmutableList.of(new MaterialStack(Materials.Carbon,2),new MaterialStack(Materials.Hydrogen,3),new MaterialStack(Materials.Chlorine,1)),EXT_METAL | IngotMaterial.MatFlags.GENERATE_FOIL);
        VinylChloride = new FluidMaterial(988,"vinyl_chloride",0xb0bbbb,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Carbon,2),new MaterialStack(Materials.Hydrogen,3),new MaterialStack(Materials.Chlorine,1)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        Ethylene = new FluidMaterial(987,"ethylene",0xadadad,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Carbon,2),new MaterialStack(Materials.Hydrogen,4)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        CharcoalByproducts = new FluidMaterial(986,"charcoal_byproducts",0x664027,MaterialIconSet.FLUID,ImmutableList.of(),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DISABLE_DECOMPOSITION);
        Benzene = new FluidMaterial(985,"benzene",0x1f1f1f,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Carbon,6),new MaterialStack(Materials.Hydrogen,6)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        WoodGas = new FluidMaterial(984,"wood_gas",0xb1a571,MaterialIconSet.GAS,ImmutableList.of(),FluidMaterial.MatFlags.STATE_GAS | Material.MatFlags.DISABLE_DECOMPOSITION);
        WoodVinegar = new FluidMaterial(983,"wood_vinegar",0xa54b0f,MaterialIconSet.FLUID,ImmutableList.of(),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DISABLE_DECOMPOSITION);
        WoodTar = new FluidMaterial(982,"wood_tar",0x2d2118,MaterialIconSet.FLUID,ImmutableList.of(),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DISABLE_DECOMPOSITION);
        SodiumHydroxide = new DustMaterial(981,"sodium_hydroxide",0x001942,MaterialIconSet.DULL,1,ImmutableList.of(new MaterialStack(Materials.Sodium,1),new MaterialStack(Materials.Oxygen,1),new MaterialStack(Materials.Hydrogen,1)),Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        Quicklime = new DustMaterial(980,"quicklime",0x808080,MaterialIconSet.SAND,1,ImmutableList.of(new MaterialStack(Materials.Calcium,1),new MaterialStack(Materials.Oxygen,1)),Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        Acetone = new FluidMaterial(979,"acetone",0x8e8e8e,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Carbon,3),new MaterialStack(Materials.Hydrogen,6),new MaterialStack(Materials.Oxygen,1)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        SulfurTrioxide = new FluidMaterial(978,"sulfur_trioxide",0x83831d,MaterialIconSet.GAS,ImmutableList.of(new MaterialStack(Materials.Sulfur,1),new MaterialStack(Materials.Oxygen,3)),FluidMaterial.MatFlags.STATE_GAS | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        SulfurDioxide = new FluidMaterial(977,"sulfur_dioxide",0x9c9c20,MaterialIconSet.GAS,ImmutableList.of(new MaterialStack(Materials.Sulfur,1),new MaterialStack(Materials.Oxygen,2)),FluidMaterial.MatFlags.STATE_GAS | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        Glycerol = new FluidMaterial(976,"glycerol",0x70af70,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Carbon,3),new MaterialStack(Materials.Hydrogen,8),new MaterialStack(Materials.Oxygen,3)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        FishOil = new FluidMaterial(975,"fish_oil",0xdcc15d,MaterialIconSet.FLUID,ImmutableList.of(),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DISABLE_DECOMPOSITION);
        Methanol = new FluidMaterial(974,"methanol",0x887010,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Carbon,1),new MaterialStack(Materials.Hydrogen,4),new MaterialStack(Materials.Oxygen,1)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        CarbonMonoxde = new FluidMaterial(973,"carbon_monoxide",0x19436c,MaterialIconSet.GAS,ImmutableList.of(new MaterialStack(Materials.Carbon,1),new MaterialStack(Materials.Oxygen,1)),FluidMaterial.MatFlags.STATE_GAS | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        CetaneBoostedDiesel = new FluidMaterial(972,"cetane_boosted_diesel",0xc1cf31,MaterialIconSet.FLUID,ImmutableList.of(),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DISABLE_DECOMPOSITION);
        DilutedSulfuricAcid = new FluidMaterial(971,"diluted_sulfuric_acid",0x986526,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Hydrogen,2),new MaterialStack(Materials.Sulfur,1),new MaterialStack(Materials.Oxygen,4)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DISABLE_DECOMPOSITION);
        SodiumBisulfate = new DustMaterial(970,"sodium_bisulfate",0x002833,MaterialIconSet.DULL,1,ImmutableList.of(new MaterialStack(Materials.Sodium,1),new MaterialStack(Materials.Hydrogen,1),new MaterialStack(Materials.Sulfur,1),new MaterialStack(Materials.Oxygen,4)),Material.MatFlags.DISABLE_DECOMPOSITION);
        Chloroform = new FluidMaterial(969,"chloroform",0x702e80,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Carbon,1),new MaterialStack(Materials.Hydrogen,1),new MaterialStack(Materials.Chlorine,3)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        DilutedHydrochloricAcid = new FluidMaterial(968,"diluted_hydrochloric_acid",0x7c8684,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Hydrogen,1),new MaterialStack(Materials.Chlorine,1)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DISABLE_DECOMPOSITION);
        HypochlorousAcid = new FluidMaterial(967,"hypochlorous_acid",0x5d7075,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Hydrogen,1),new MaterialStack(Materials.Chlorine,1),new MaterialStack(Materials.Oxygen,1)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        Ammonia = new FluidMaterial(966,"ammonia",0x3d356b,MaterialIconSet.GAS,ImmutableList.of(new MaterialStack(Materials.Nitrogen,1),new MaterialStack(Materials.Hydrogen,3)),FluidMaterial.MatFlags.STATE_GAS | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        Chloramine = new FluidMaterial(965,"chloramine",0x3d836c,MaterialIconSet.GAS,ImmutableList.of(new MaterialStack(Materials.Nitrogen,1),new MaterialStack(Materials.Hydrogen,2),new MaterialStack(Materials.Chlorine,1)),FluidMaterial.MatFlags.STATE_GAS | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        Dimethylamine = new FluidMaterial(964,"dimethylamine",0x4b3f59,MaterialIconSet.GAS,ImmutableList.of(new MaterialStack(Materials.Carbon,2),new MaterialStack(Materials.Hydrogen,7),new MaterialStack(Materials.Nitrogen,1)),FluidMaterial.MatFlags.STATE_GAS | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        Dimethylhydrazine = new FluidMaterial(963,"dimethylhidrazine",0x10104c,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Carbon,2),new MaterialStack(Materials.Hydrogen,8),new MaterialStack(Materials.Nitrogen,2)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DISABLE_DECOMPOSITION);
        RocketFuel = new FluidMaterial(962,"rocket_fuel",0xbdb78c,MaterialIconSet.FLUID,ImmutableList.of(),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DISABLE_DECOMPOSITION);
        DinitrogenTetroxide = new FluidMaterial(961,"dinitrogen_tetroxide",0x0f3d6e,MaterialIconSet.GAS,ImmutableList.of(new MaterialStack(Materials.Nitrogen,2),new MaterialStack(Materials.Oxygen,4)),FluidMaterial.MatFlags.STATE_GAS | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        SiliconeRubber = new IngotMaterial(960,"silicon_rubber",0xacacac,MaterialIconSet.DULL,1,ImmutableList.of(new MaterialStack(Materials.Carbon,2),new MaterialStack(Materials.Hydrogen,6),new MaterialStack(Materials.Oxygen,1),new MaterialStack(Materials.Silicon,1)),Material.MatFlags.DISABLE_DECOMPOSITION);
        Polydimethylsiloxane = new DustMaterial(959,"polydimethylsiloxane",0x8c8c8c,MaterialIconSet.DULL,1,ImmutableList.of(new MaterialStack(Materials.Carbon,2),new MaterialStack(Materials.Hydrogen,6),new MaterialStack(Materials.Oxygen,1),new MaterialStack(Materials.Silicon,1)),Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        Dimethyldichlorosilane = new FluidMaterial(958,"dimethyldichlorosilane",0x3e1c47,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Carbon,2),new MaterialStack(Materials.Hydrogen,6),new MaterialStack(Materials.Chlorine,2),new MaterialStack(Materials.Silicon,1)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        Styrine = new FluidMaterial(957,"styrine",0xa39c95,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Carbon,8),new MaterialStack(Materials.Hydrogen,8)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        Polysterine = new IngotMaterial(956,"polystyrine",0x888079,MaterialIconSet.DULL,1,ImmutableList.of(new MaterialStack(Materials.Carbon,8),new MaterialStack(Materials.Hydrogen,8)),Material.MatFlags.DISABLE_DECOMPOSITION);
        Butadiene = new FluidMaterial(955,"butadiene",0xb55a10,MaterialIconSet.GAS,ImmutableList.of(new MaterialStack(Materials.Carbon,4),new MaterialStack(Materials.Hydrogen,6)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        RawStyrineButadieneRubber = new DustMaterial(954,"raw_styrine_butadiene_rubber",0x4f3c3a,MaterialIconSet.SAND,1,ImmutableList.of(new MaterialStack(Materials.Carbon,8),new MaterialStack(Materials.Hydrogen,8),new MaterialStack(GAMaterials.Butadiene,3)),Material.MatFlags.DISABLE_DECOMPOSITION);
        StyrineButadieneRubber = new IngotMaterial(953,"styrine_butadiene_rubber",0x0e0b0a,MaterialIconSet.ROUGH,1,ImmutableList.of(new MaterialStack(Materials.Carbon,8),new MaterialStack(Materials.Hydrogen,8),new MaterialStack(GAMaterials.Butadiene,3)),Material.MatFlags.DISABLE_DECOMPOSITION);
        Dichlorobenzene = new FluidMaterial(952,"dichlorobenzene",0x0d3f4b,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Carbon,6),new MaterialStack(Materials.Hydrogen,4),new MaterialStack(Materials.Chlorine,2)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        HydrochloricAcid = new FluidMaterial(951,"hydrochloric_acid",0x909c99,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Hydrogen,1),new MaterialStack(Materials.Chlorine,1)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        AceticAcid = new FluidMaterial(950,"acetic_acid",0x9c8e80,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Carbon,2),new MaterialStack(Materials.Hydrogen,4),new MaterialStack(Materials.Oxygen,2)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        FermentedBiomass = new FluidMaterial(949,"fermented_biomass",0x3f4b0d,MaterialIconSet.FLUID,ImmutableList.of(),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DISABLE_DECOMPOSITION);
        Potash = new DustMaterial(948,"potash",0x4d2a23,MaterialIconSet.SAND,1,ImmutableList.of(new MaterialStack(Materials.Potassium,2),new MaterialStack(Materials.Oxygen,1)),Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        SodaAsh = new DustMaterial(947,"soda_ash",0x757588,MaterialIconSet.SAND,1,ImmutableList.of(new MaterialStack(Materials.Sodium,2),new MaterialStack(Materials.Carbon,1),new MaterialStack(Materials.Oxygen,3)),Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        HydrofluoricAcid = new FluidMaterial(946,"hydrofluoric_acid",0x0e6f87,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Hydrogen,1),new MaterialStack(Materials.Fluorine,1)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        NitricOxide = new FluidMaterial(945,"nitric_oxide",0x679cb8,MaterialIconSet.GAS,ImmutableList.of(new MaterialStack(Materials.Nitrogen,1),new MaterialStack(Materials.Oxygen,1)),FluidMaterial.MatFlags.STATE_GAS | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        MethylAcetate = new FluidMaterial(944,"methyl_acetate",0xbd9f8e,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Carbon,3),new MaterialStack(Materials.Hydrogen,6),new MaterialStack(Materials.Oxygen,2)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        Ethenone = new FluidMaterial(943,"ethenone",0x1b1b41,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Carbon,2),new MaterialStack(Materials.Hydrogen,2),new MaterialStack(Materials.Oxygen,1)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        Tetranitromethane = new FluidMaterial(942,"tetranitromethane",0x1a2c2c,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Carbon,1),new MaterialStack(Materials.Nitrogen,4),new MaterialStack(Materials.Oxygen,8)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        BioDiesel = new FluidMaterial(941,"bio_diesel",0xc3690f,MaterialIconSet.FLUID,ImmutableList.of(),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DISABLE_DECOMPOSITION);
        RawGrowthMedium = new FluidMaterial(940,"raw_growth_medium",0xa47351,MaterialIconSet.FLUID,ImmutableList.of(),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DISABLE_DECOMPOSITION);
        SterilizedGrowthMedium = new FluidMaterial(939,"sterilized_growth_medium",0xac876e,MaterialIconSet.FLUID,ImmutableList.of(),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DISABLE_DECOMPOSITION);
        Meat = new DustMaterial(938,"meat",0xc14c4c,MaterialIconSet.SAND,1,ImmutableList.of(),Material.MatFlags.DISABLE_DECOMPOSITION);
        CookedMeat = new DustMaterial(937,"cooked_meat",0x712d0f,MaterialIconSet.SAND,1,ImmutableList.of(),Material.MatFlags.DISABLE_DECOMPOSITION);
        VinylAcetate = new FluidMaterial(936,"vinyl_acetate",0xc8916c,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Carbon,4),new MaterialStack(Materials.Hydrogen,6),new MaterialStack(Materials.Oxygen,2)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        GalliumArsenide = new IngotMaterial(935,"gallium_arsenide",0x727272,MaterialIconSet.DULL,1,ImmutableList.of(new MaterialStack(Materials.Arsenic,1),new MaterialStack(Materials.Gallium,1)),Material.MatFlags.DECOMPOSITION_BY_CENTRIFUGING | DustMaterial.MatFlags.GENERATE_PLATE,(Element)null,1200);
        PolyphenyleneSulfide = new IngotMaterial(934,"polyphenylene_sulfide",0x856a00,MaterialIconSet.DULL,1,ImmutableList.of(new MaterialStack(Materials.Carbon,6),new MaterialStack(Materials.Hydrogen,4),new MaterialStack(Materials.Sulfur,1)),Material.MatFlags.DISABLE_DECOMPOSITION);
        NickelSulfateSolution = new FluidMaterial(933,"nickel_sulfate_water_solution",0x3eb640,MaterialIconSet.FLUID,ImmutableList.of(),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DISABLE_DECOMPOSITION);
        BlueVitriolSolution = new FluidMaterial(932,"blue_vitriol_water_solution",0x48a5c0,MaterialIconSet.FLUID,ImmutableList.of(),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DISABLE_DECOMPOSITION);
        Propane = new FluidMaterial(931,"propane",0xc4b348,MaterialIconSet.GAS,ImmutableList.of(new MaterialStack(Materials.Carbon,3),new MaterialStack(Materials.Hydrogen,8)),FluidMaterial.MatFlags.STATE_GAS | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        Propene = new FluidMaterial(930,"propene",0xc5ad4c,MaterialIconSet.GAS,ImmutableList.of(new MaterialStack(Materials.Carbon,3),new MaterialStack(Materials.Hydrogen,6)),FluidMaterial.MatFlags.STATE_GAS | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        Ethane = new FluidMaterial(929,"ethane",0x9d9dc4,MaterialIconSet.GAS,ImmutableList.of(new MaterialStack(Materials.Carbon,2),new MaterialStack(Materials.Hydrogen,6)),FluidMaterial.MatFlags.STATE_GAS | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        Butene = new FluidMaterial(928,"butene",0xa34711,MaterialIconSet.GAS,ImmutableList.of(new MaterialStack(Materials.Carbon,4),new MaterialStack(Materials.Hydrogen,8)),FluidMaterial.MatFlags.STATE_GAS | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        Butane = new FluidMaterial(927,"butane",0x8f3624,MaterialIconSet.GAS,ImmutableList.of(new MaterialStack(Materials.Carbon,4),new MaterialStack(Materials.Hydrogen,10)),FluidMaterial.MatFlags.STATE_GAS | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        CalciumAcetate = new FluidMaterial(926,"calcium_acetate",0xae9f91,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Calcium,1),new MaterialStack(Materials.Carbon,2),new MaterialStack(Materials.Oxygen,4),new MaterialStack(Materials.Hydrogen,6)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        Cumene = new FluidMaterial(925,"cumene",0x4b250c,MaterialIconSet.FLUID,ImmutableList.of(new MaterialStack(Materials.Carbon,9),new MaterialStack(Materials.Hydrogen,12)),FluidMaterial.MatFlags.GENERATE_FLUID_BLOCK | Material.MatFlags.DECOMPOSITION_BY_ELECTROLYZING);
        IndiumGalliumPhosphide = new IngotMaterial(924,"indium_gallium_phosphide",0x7d6d94,MaterialIconSet.DULL,1,ImmutableList.of(new MaterialStack(Materials.Indium,1),new MaterialStack(Materials.Gallium,1),new MaterialStack(Materials.Phosphorus,1)),Material.MatFlags.DECOMPOSITION_BY_CENTRIFUGING | DustMaterial.MatFlags.GENERATE_PLATE);
        PlatinumGroupSludge = new DustMaterial(923,"platinum_group_sludge",0x001300,MaterialIconSet.POWDER,1,ImmutableList.of(),Material.MatFlags.DISABLE_DECOMPOSITION);
    }
}